syntax = "proto3";

package wings.v1;

service CatalogService {
  rpc CreateCatalog(CreateCatalogRequest) returns (CreateCatalogResponse);

  rpc GetCatalog(GetCatalogRequest) returns (GetCatalogResponse);

  rpc DeleteCatalog(DeleteCatalogRequest) returns (DeleteCatalogResponse);

  rpc LinkTable(LinkTableRequest) returns (LinkTableResponse);

  rpc UnlinkTable(UnlinkTableRequest) returns (UnlinkTableResponse);

  rpc LoadTable(LoadTableRequest) returns (LoadTableResponse);
}

message CreateCatalogRequest {
  // The ID to use for the catalog, which will become the final component
  // of the catalog's resource name.
  //
  // This value should be 1-63 characters, and valid characters
  // are /[a-z][a-z0-9_-]*/.
  string catalog_id = 1;

  CatalogConfig config = 2;
}

message CreateCatalogResponse {}

message GetCatalogRequest {
  string name = 1;
}

message GetCatalogResponse {
  Catalog catalog = 1;
}

message DeleteCatalogRequest {
  string name = 1;
}

message DeleteCatalogResponse {}

message LinkTableRequest {
  // The resource name of the catalog to link the table from, e.g.
  // `catalogs/my-catalog`.
  string catalog = 1;

  // The identifier of the table to link.
  TableIdentifier table = 2;
}

message LinkTableResponse {
  // The UUID of the linked table.
  string table_uuid = 1;
}

message UnlinkTableRequest {
  // The resource name of the catalog to unlink the table from, e.g.
  // `catalogs/my-catalog`.
  string catalog = 1;

  // The identifier of the table to unlink.
  TableIdentifier table = 2;
}

message UnlinkTableResponse {}

message LoadTableRequest {
  // The resource name of the catalog to load the table from, e.g.
  // `catalogs/my-catalog`.
  string catalog = 1;

  // The identifier of the table to load.
  TableIdentifier table = 2;
}

message LoadTableResponse {
  // The UUID of the table.
  string table_uuid = 1;
}

message Catalog {
  string name = 1;

  CatalogConfig config = 2;
}

message CatalogConfig {
  oneof config {
    RestCatalogConfig rest = 1;
  }
}

message RestCatalogConfig {
  string uri = 1;

  optional string warehouse = 2;

  map<string, string> properties = 3;
}

message TableIdentifier {
  // The components of the table's namespace.
  repeated string namespace = 1;

  // The name of the table.
  string name = 2;
}
