syntax = "proto3";

package wings.v1;

service CatalogService {
  rpc CreateCatalog(CreateCatalogRequest) returns (CreateCatalogResponse);

  rpc GetCatalog(GetCatalogRequest) returns (GetCatalogResponse);

  rpc DeleteCatalog(DeleteCatalogRequest) returns (DeleteCatalogResponse);
}

message CreateCatalogRequest {
  // The ID to use for the catalog, which will become the final component
  // of the catalog's resource name.
  //
  // This value should be 1-63 characters, and valid characters
  // are /[a-z][a-z0-9_-]*/.
  string catalog_id = 1;

  CatalogConfig config = 2;
}

message CreateCatalogResponse {}

message GetCatalogRequest {
  string name = 1;
}

message GetCatalogResponse {
  Catalog catalog = 1;
}

message DeleteCatalogRequest {
  string name = 1;
}

message DeleteCatalogResponse {}

message Catalog {
  string name = 1;

  CatalogConfig config = 2;
}

message CatalogConfig {
  oneof config {
    RestCatalogConfig rest = 1;
  }
}

message RestCatalogConfig {
  string uri = 1;

  optional string warehouse = 2;

  map<string, string> properties = 3;
}
