[package]
name = "wings"
edition.workspace = true
authors.workspace = true
version.workspace = true
license.workspace = true

[lib]
name = "wings"
path = "src/lib.rs"

[[bin]]
name = "wings"
path = "src/main.rs"

[dependencies]
clap.workspace = true
object_store.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true

wings-common.workspace = true
wings-grpc-server.workspace = true
wings-meta-store.workspace = true
wings-observability.workspace = true
wings-secret-store.workspace = true
